### ISSUE TITLE
 emis index is out of bounds for axis 1

### ISSUE THREAD

**Issue by xigrug** [jinfan0931/meic2wrf#11]
> Traceback (most recent call last):
>   File "meic2wrf_noGUI.py", line 253, in <module>
>     itp_dis(ent_inp,ent_dir,save_dir)
>   File "meic2wrf_noGUI.py", line 115, in itp_dis
>     for emis in section]
>   File "meic2wrf_noGUI.py", line 115, in <listcomp>
>     for emis in section]
>   File "/public/home/hysplit/data/emis/meic2wrf-master/int_dis.py", line 65, in meic2wrf
>     emis_inp[y_cnt,x_cnt] = inp_p(pnt_lat, pnt_lon) #assign meic emission
>   File "/public/home/hysplit/data/emis/meic2wrf-master/int_dis.py", line 58, in inp_p
>     return inp(ix, iy, dx, dy, cdx, cdy)
>   File "/public/home/hysplit/data/emis/meic2wrf-master/int_dis.py", line 46, in inp
>     return emis[ix,iy]*cdx*cdy+emis[ix,iy+1]*cdx*dy+emis[ix+1,iy+1]*dx*dy+emis[ix+1,iy]*dx*cdy
> IndexError: index 320 is out of bounds for axis 1 with size 320

运行WRF-3.3.1的input文件出错，示例input文件没问题，这个是有什么问题呢？

**Comment by xigrug** [comment]
> 
不知道是不是第一层区域过大导致的，试了domain03可以运行，不能超出中国区域么？这样也不合理呢，有些地区嵌套难免稍微跨越点国境。
