### ISSUE TITLE
您好，在运行脚本时出现了关于_tkinter的报错

### ISSUE THREAD

**Issue by SherlockLupin-code** [jinfan0931/meic2wrf#9]
在运行meic2wrf_GUI.py是出现了以下报错，根据网上的办法也没有解决，
目前的运行平台是WSL，python3.8版本，想请教一下这个问题
Traceback (most recent call last):
  File "meic2wrf_GUI.py", line 23, in <module>
    root=tk.Tk()
  File "/home/sherlock/miniconda3/envs/python/lib/python3.8/tkinter/__init__.py", line 2261, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by SherlockLupin-code** [comment]
是不是只有在3.7.7的版本下运行才可以
